# $Id: Makefile.kmk 2420 2010-10-17 00:33:38Z bird $
## @file
# Tests - Top Level Makefile.
#

#
# Copyright (c) 2008-2010 knut st. osmundsen <bird-kBuild-spamx@anduin.net>
#
# This file is part of kBuild.
#
# kBuild is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# kBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kBuild; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
#


include $(PATH_KBUILD)/header.kmk

SUBDIRS = \
	inherit-target \
	inherit-bld \
	inherit-misc \

SUBDIRS.os2 = \
	os2-impdef

include $(FILE_KBUILD_FOOTER)
