#!/bin/sh

# Redirect output from a builtin command.

. ${KASH_TEST_DIR}/common-include.sh

TMPFILE="/tmp/redirect-1.$$.tmp"

echo 1 > $TMPFILE
VAR=`$CMD_CAT $TMPFILE`
$CMD_RM -f $TMPFILE
if test "$VAR" != "1"; then
    echo "redirect-1: FAILURE - VAR=$VAR"
    exit 1
fi
echo "redirect-1: SUCCESS"
exit 0

