# $Id: Makefile.kmk 2413 2010-09-11 17:43:04Z bird $
## @file
# Test - Misc Inheritance.
#

#
# Copyright (c) 2008-2010 knut st. osmundsen <bird-kBuild-spamx@anduin.net>
#
# This file is part of kBuild.
#
# kBuild is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# kBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with kBuild; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
#


DEPTH = ../..
include $(PATH_KBUILD)/header.kmk

#
# Search for SDKs in the current directory.
#
KBUILD_SDK_PATHS := $(PATH_SUB_CURRENT)

#
# Tests for checking that prepending and appending of properties
# that have been defined as simple variables work. Ticket #51.
# (This is a little bit out of place, but so what.)
#
PROGRAMS += inherit-misc51a
inherit-misc51a_TEMPLATE := tmpl51a
inherit-misc51a_SDKS := sdk51a-xz
inherit-misc51a_DEFS := X=z
inherit-misc51a_SOURCES := ../dummy_defined_X.c

TEMPLATE_tmpl51a = inherit-misc51 template
TEMPLATE_tmpl51a_EXTENDS = TST
TEMPLATE_tmpl51a_DEFS = $(SDK_sdk51a-xz_SPECIAL_DEFS)

include $(FILE_KBUILD_FOOTER)

